config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get 'static_pages/home'
  get 'sessions/new'

  resources :reactions
  resources :user_skills
  resources :skills
  resources :users
  # デバッグ用　ユーザー管理一覧
  get '/users_list', to: 'users#list'

  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  # ユーザープロフィールからスキルを追加する用
  post '/users/:user_id/add_skill', to: 'users#add_skill'
  # ユーザープロフィールからスキルに+1を追加する用
  post '/users/:user_id/:skill_id', to: 'users#add_reaction'
  # ユーザープロフィールからスキルを削除する時
  delete '/users/:id/skill_delete/:skill_id', to: 'user_skills#delete'
    # ユーザープロフィールからリアクションを削除する時
  delete '/users/:id/reaction_delete/:skill_id', to: 'reactions#delete'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user_skill.rb
class UserSkill < ApplicationRecord
  belongs_to :user
  belongs_to :skill
  has_many :reactions, :dependent => :destroy
  validates :user,presence: true
  validates :skill,presence: true
end

app/controllers/user_skills_controller.rb
class UserSkillsController < ApplicationController
  before_action :set_user_skill, only: [:show, :edit, :update, :destroy]

  # GET /user_skills
  # GET /user_skills.json
  def index
    @user_skills = UserSkill.all
  end

  # GET /user_skills/1
  # GET /user_skills/1.json
  def show
  end

  # GET /user_skills/new
  def new
    @user_skill = UserSkill.new
  end

  # GET /user_skills/1/edit
  def edit
  end

  # POST /user_skills
  # POST /user_skills.json
  def create
    @user_skill = UserSkill.new(user_skill_params)

    respond_to do |format|
      if @user_skill.save
        format.html { redirect_to @user_skill, notice: 'User skill was successfully created.' }
        format.json { render :show, status: :created, location: @user_skill }
      else
        format.html { render :new }
        format.json { render json: @user_skill.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_skills/1
  # PATCH/PUT /user_skills/1.json
  def update
    respond_to do |format|
      if @user_skill.update(user_skill_params)
        format.html { redirect_to @user_skill, notice: 'User skill was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_skill }
      else
        format.html { render :edit }
        format.json { render json: @user_skill.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_skills/1
  # DELETE /user_skills/1.json
  def destroy
    @user_skill.destroy
    respond_to do |format|
      format.html { redirect_to user_skills_url, notice: 'User skill was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # プロフィールからスキルの追加を消す
  def delete
    
    if params[:id].to_i == current_user.id 
      user_skill = UserSkill.where(user_id: params[:id],skill_id: params[:skill_id]).first
      user_skill.destroy
      flash[:success] = "スキルを削除しました"
      redirect_to :back
    else
      flash[:danger] = "スキルを削除できませんでした"
      redirect_to :back
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_skill
      @user_skill = UserSkill.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_skill_params
      params.require(:user_skill).permit(:user_id, :skill_id)
    end
end

app/helpers/user_skills_helper.rb
module UserSkillsHelper
end

app/views/user_skills/_form.html.erb
<%= form_for(user_skill) do |f| %>
  <% if user_skill.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user_skill.errors.count, "error") %> prohibited this user_skill from being saved:</h2>

      <ul>
      <% user_skill.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.number_field :user_id %>
  </div>

  <div class="field">
    <%= f.label :skill_id %>
    <%= f.number_field :skill_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/user_skills/edit.html.erb
<h1>Editing User Skill</h1>

<%= render 'form', user_skill: @user_skill %>

<%= link_to 'Show', @user_skill %> |
<%= link_to 'Back', user_skills_path %>

app/views/user_skills/index.html.erb
<p id="notice"><%= notice %></p>

<h1>User Skills</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Skill</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_skills.each do |user_skill| %>
      <tr>
        <td><%= user_skill.user_id %></td>
        <td><%= user_skill.skill_id %></td>
        <td><%= link_to 'Show', user_skill %></td>
        <td><%= link_to 'Edit', edit_user_skill_path(user_skill) %></td>
        <td><%= link_to 'Destroy', user_skill, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User Skill', new_user_skill_path %>

app/views/user_skills/new.html.erb
<h1>New User Skill</h1>

<%= render 'form', user_skill: @user_skill %>

<%= link_to 'Back', user_skills_path %>

app/views/user_skills/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @user_skill.user_id %>
</p>

<p>
  <strong>Skill:</strong>
  <%= @user_skill.skill_id %>
</p>

<%= link_to 'Edit', edit_user_skill_path(@user_skill) %> |
<%= link_to 'Back', user_skills_path %>